# Generated by Django 5.0.9 on 2024-12-01 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPrincipal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='es_administrador',
            field=models.BooleanField(default=False),
        ),
    ]
